services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prn232-lab1-database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Lab1_Strong_Password123!"
    ports:
      - "1433:1433"
    volumes:
      - prn232-lab1-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    container_name: prn232-lab1-api
    build:
      context: .
      dockerfile: PRN232.LMS.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: "Server=database,1433;Database=PRN232Lab1;User Id=sa;Password=Lab1_Strong_Password123!;TrustServerCertificate=True;Encrypt=False"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

volumes:
  prn232-lab1-sql-data:
